### ISSUE TITLE
Implement before_install for Travis arm64 job

### ISSUE THREAD

**Issue by barrbrain** [xiph/rav1e#1771]
The current configuration skips `before_install` because it is only implemented for an `x86_64` host.
```yaml
- name: "Arm build and test"
  rust: stable
  arch: arm64
  before_install: skip
  script:
    - cargo build --release --tests --verbose
    - cargo test --release --verbose
```

See the scripts in the `.travis` directory:
- `install-aom.sh`
- `install-dav1d.sh`
- `install-kcov.sh`
- `install-nasm.sh`
- `install-sccache.sh`
